travis:
  secure:
    BINSTAR_TOKEN: ZdD3onay3pYymMMqBnkiKwdmS5tCKFdWHhMvaaSiMuSw6MjqmgD4yW42Ka0TjvViTwQWAFhOkJm5lDleHAas/F81CZqJ56SJYJdNMsxCjkzqZQSK4B2Rq6Kg3zzlNpkaHVjRh6GRZYK/HVzALC/r71Q7ssge+t7BRv+pomJ1gqFwwpaBfS9tqzxqBmUpg6JhmyCLZX+YqJhCbFy3XSV0E5y5IdDLRRUC27VOiMK307WgS6qXLn8RETGMSG9K9FqXru2Ln5bZIvtwQZNOTeBw1pw8o3dafEdZ8QONMqd+OZdSNRx3affrD6uvIMYvtu2jX8cEzg7r7cGsmNFbMu0PYlGZ6tQ74QrGCRjMwNiTaUp8ySVvWVv0Yk6azFHVoKwIAHS20I+cTyCT5N8/VcUOCCPjQC6pDoP0SjNGaKr7uI6yk4w+NMm84JL8CD8Q5XLJ5HEZ+zbpBYc21DxGshHYgw1B/VlrglBT5W4CF2Gds0iYYgX1Q/uZmEjlcpgB7raJTk+PzGF/D/krAwSF7jgN+8yVflkTVhayDjdJUCgWcZLgrPh0NCgH73gRIBKsHqXjvI913FKhC4W8OLwI4RVhbgZNOePEsTWwoZeP4Fs+syb2/1SvyUyYe6bFtl1tLb5rGhsKP3TXqbyHWGU1fciyQsBXO5s8bqGmNJb5MScDULs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
