travis:
  secure:
    BINSTAR_TOKEN: qJvhhgsgA8ovTAr7HoVhsakWhy9Gab+fTM8kx97qEdPfmjZ1TVeIHP2SxVJ0texzVP4phL4lzLMTKIf/MS1HnGVFrPFbSrxuvSPEye/SUVvb7/d9/qNNzcfjneshUr5KKHPkTVBvf4Z3o34cesV1eQ9vQ3hg9IUAL78i2jjIlfcVYJztoZCaAp4w35XXvdcCekwzJ4ic6Yxz34qkuQOxRnQRiteGmlCbNGsk6g8zDsG0PZY25Z2ExLfmP2jMqGeDn2iJ8J333qeHTcGXw+J/7sC86+p1o9yLYnbROMt1gO/UChwOWYB+vo+ruzkvqFnTXIb/ed75Vv0hM8mwfZCkuVI4DeqW7i4bT+nE/8VlaI/5yoX0iM2CZZlOezjbbfeqBa8DNjgBn3Ity9ZlZHs8ATEBDMWPaAK80psT+QQgvyz4YXDqHcpafl7K9SOAzhMA5Rnm3/nwTPLBM+9FJmmoQgSMB3hAhW1b2Ya3McOdDHJZfSbs8EllXthl6LU4u9+W4Z2oXCAbf0Ss3KdWavmN1B0loKJZ7BOiU+mzUfIzund23ftasUwU3RzVJbQKl2u6+hwACAqyFYxRr+sPRP+2dinOIdF4Vf1sjh5KyEwOK7u6kH8wq8HyMZ8TRdwhXUP4SSx7lXM2pKI/FyJFZ5GjVwGJnLXhfK6A9JDivtaUfw8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
